version: '2'
services:
    web:
        image: website
        build:
            context: ./
            dockerfile: ./app.docker
        volumes:
            - ./:/var/www/html
        ports:
            - "8088:80"
        links:
            - mysql:mysql
    mysql:
        image: mysql
        volumes:
            - mysql_data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        environment:
            - "PMA_HOST=mysql"
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=todoDb"
            - "MYSQL_USER=jnpl"
            - "MYSQL_PASSWORD=johnpaul"
        ports:
            - "3308:3306"
        expose:
            - '3308'
volumes:
    mysql_data:
        driver: local